env:
  commonjs: true
  es2021: true
  jest: true
  node: true
extends:
  # Todo: check rules
  - 'eslint:recommended'
  # Todo: check rules
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
root: true
rules:
  # Possible Errors
  no-console: error

  # Best Practices
  array-callback-return: error
  block-scoped-var: error
  consistent-return: error
  curly: error
  default-case: error
  default-case-last: error
  default-param-last: error
  eqeqeq: error
  grouped-accessor-pairs:
    - error
    - getBeforeSet
  guard-for-in: error
  max-classes-per-file: error
  no-caller: error
  no-constructor-return: error
  no-else-return:
    - error
    - allowElseIf: false
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  no-magic-numbers:
    - off
    - ignoreArrayIndexes: true
      ignoreDefaultValues: true
  no-multi-spaces: error
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-nonoctal-decimal-escape: error
  no-octal-escape: error
  no-param-reassign: error
  no-proto: error
  no-return-assign:
    - error
    - always
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-return: error
  no-void: error
  no-warning-comments:
    - warn
    - terms:
        - todo
      location: start
  prefer-named-capture-group: warn
  prefer-promise-reject-errors: error
  prefer-regex-literals:
    - error
    - disallowRedundantWrapping: true
  radix: error
  require-await: error
  require-unicode-regexp: error
  vars-on-top: error
  wrap-iife: error
  yoda: error

  # Strict mode
  strict: error

  # Variables
  no-label-var: error
  no-undefined: error
  no-use-before-define: error

  # ECMAScript 6
  no-confusing-arrow: error
  no-duplicate-imports: error
  no-useless-computed-key: error
  no-useless-rename: error
  no-var: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  rest-spread-spacing: error
