export enum ScssRuleName {
  AtEachKeyValueSingleLine = 'scss/at-each-key-value-single-line',
  AtExtendNoMissingPlaceholder = 'scss/at-extend-no-missing-placeholder',
  AtFunctionNamedArguments = 'scss/at-function-named-arguments',
  AtFunctionPattern = 'scss/at-function-pattern',
  AtIfNoNull = 'scss/at-if-no-null',
  AtImportNoPartialLeadingUnderscore = 'scss/at-import-no-partial-leading-underscore',
  AtImportPartialExtension = 'scss/at-import-partial-extension',
  AtMixinNamedArguments = 'scss/at-mixin-named-arguments',
  AtMixinPattern = 'scss/at-mixin-pattern',
  AtRuleNoUnknown = 'scss/at-rule-no-unknown',
  CommentNoEmpty = 'scss/comment-no-empty',
  DimensionNoNonNumericValues = 'scss/dimension-no-non-numeric-values',
  DollarVariableNoMissingInterpolation = 'scss/dollar-variable-no-missing-interpolation',
  DollarVariablePattern = 'scss/dollar-variable-pattern',
  FunctionColorRelative = 'scss/function-color-relative',
  FunctionQuoteNoQuotedStringsInside = 'scss/function-quote-no-quoted-strings-inside',
  FunctionUnquoteNoUnquotedStringsInside = 'scss/function-unquote-no-unquoted-strings-inside',
  MapKeysQuotes = 'scss/map-keys-quotes',
  NoDuplicateMixins = 'scss/no-duplicate-mixins',
  NoGlobalFunctionNames = 'scss/no-global-function-names',
  PercentPlaceholderPattern = 'scss/percent-placeholder-pattern',
  SelectorNoRedundantNestingSelector = 'scss/selector-no-redundant-nesting-selector',
}
