rules:
  at-rule-disallowed-list:
    - import
    - debug
  at-rule-no-vendor-prefix: true
  block-no-empty:
    - true
    - ignore:
        - comments
  color-named: never
  color-no-invalid-hex: true
  comment-no-empty: true
  custom-media-pattern:
    - ^[a-z]+([a-z0-9-]+[a-z0-9]+)?$
    - message: Custom media should be written in lower kebab case (custom-media-pattern)
  custom-property-pattern:
    - ^[a-z]+([a-z0-9-]+[a-z0-9]+)?$
    - message: Custom property should be written in lower kebab case (custom-property-pattern)
  declaration-block-no-duplicate-custom-properties: true
  declaration-block-no-duplicate-properties: true
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-property-value-disallowed-list:
    - /^border(-(top|bottom|left|right))?$/: none
    - severity: warning
  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword: true
  function-linear-gradient-no-nonstandard-direction: true
  hue-degree-notation: angle
  keyframe-declaration-no-important: true
  keyframes-name-pattern:
    - ^[a-z]+([a-z0-9-]+[a-z0-9]+)?$
    - message: Keyframe name should be written in lower kebab case (keyframes-name-pattern)
  length-zero-no-unit: true
  media-feature-name-no-unknown: true
  media-feature-name-no-vendor-prefix: true
  named-grid-areas-no-invalid: true
  no-descending-specificity: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-source: true
  no-invalid-double-slash-comments: true
  property-no-unknown:
    - true
    - ignoreAtRules:
        - counter-style
        - supports
  property-no-vendor-prefix: true
  selector-class-pattern:
    - ^[a-z]+([a-z0-9-]+[a-z0-9]+)?$
    - resolveNestedSelectors: true
      message: Selector should be written in lower kebab case (selector-class-pattern)
  selector-id-pattern:
    - ^[a-z]+([a-z0-9-]+[a-z0-9]+)?$
    - message: Selector should be written in lower kebab case (selector-id-pattern)
  selector-no-qualifying-type:
    - true
    - ignore:
        - attribute
  selector-no-vendor-prefix: true
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-colon-notation: double
  selector-pseudo-element-no-unknown: true
  shorthand-property-no-redundant-values: true
  string-no-newline: true
  unit-no-unknown: true
  value-no-vendor-prefix: true
