name: Default

env:
  NODE_VERSION: 16

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          yarn install
          yarn run build

      - name: Run linter
        run: yarn run ci:lint

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          yarn install
          yarn run build

      - name: Run tests
        run: yarn run ci:test
